steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - mythar-api/Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/mythar/mythar-api:${_TAG}
      - .
images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/mythar/mythar-api:${_TAG}
substitutions:
  _REGION: us-central1
  _TAG: v0.3.0
